import { InjectModel } from '@nestjs/mongoose';
import { Model } from 'mongoose';
import { Medication, MedicationCategoryEnum } from '../database/schemas/medication.schema';
import { Logger } from '@nestjs/common';

const logger = new Logger('SeedMedications');

export async function seedMedications(medicationModel: Model<Medication>) {
  const count = await medicationModel.countDocuments();
  if (count > 0) {
    logger.log('Medications already seeded, skipping...');
    return;
  }

  const medications = [
    {
      medicationCode: 'MED-001',
      name: 'Paracetamol',
      genericName: 'Acetaminophen',
      category: MedicationCategoryEnum.ANALGESIC,
      description: 'Pain reliever and fever reducer',
      dosageForm: 'Tablet',
      strength: '500mg',
      manufacturer: 'Generic Pharma',
      stockQuantity: 1000,
      unit: 'tablets',
      unitPrice: 0.10,
      reorderLevel: 100,
    },
    {
      medicationCode: 'MED-002',
      name: 'Amoxicillin',
      genericName: 'Amoxicillin',
      category: MedicationCategoryEnum.ANTIBIOTIC,
      description: 'Antibiotic for bacterial infections',
      dosageForm: 'Capsule',
      strength: '500mg',
      manufacturer: 'MediCorp',
      stockQuantity: 500,
      unit: 'capsules',
      unitPrice: 0.50,
      reorderLevel: 50,
    },
    {
      medicationCode: 'MED-003',
      name: 'Ibuprofen',
      genericName: 'Ibuprofen',
      category: MedicationCategoryEnum.ANALGESIC,
      description: 'NSAID for pain and inflammation',
      dosageForm: 'Tablet',
      strength: '400mg',
      manufacturer: 'Generic Pharma',
      stockQuantity: 800,
      unit: 'tablets',
      unitPrice: 0.15,
      reorderLevel: 80,
    },
    {
      medicationCode: 'MED-004',
      name: 'Lisinopril',
      genericName: 'Lisinopril',
      category: MedicationCategoryEnum.ANTIHYPERTENSIVE,
      description: 'ACE inhibitor for high blood pressure',
      dosageForm: 'Tablet',
      strength: '10mg',
      manufacturer: 'CardioMeds',
      stockQuantity: 300,
      unit: 'tablets',
      unitPrice: 0.25,
      reorderLevel: 30,
    },
    {
      medicationCode: 'MED-005',
      name: 'Metformin',
      genericName: 'Metformin',
      category: MedicationCategoryEnum.ANTIDIABETIC,
      description: 'Oral diabetes medication',
      dosageForm: 'Tablet',
      strength: '500mg',
      manufacturer: 'DiaMeds',
      stockQuantity: 600,
      unit: 'tablets',
      unitPrice: 0.20,
      reorderLevel: 60,
    },
    {
      medicationCode: 'MED-006',
      name: 'Vitamin C',
      genericName: 'Ascorbic Acid',
      category: MedicationCategoryEnum.VITAMIN,
      description: 'Vitamin C supplement',
      dosageForm: 'Tablet',
      strength: '1000mg',
      manufacturer: 'VitaHealth',
      stockQuantity: 200,
      unit: 'tablets',
      unitPrice: 0.30,
      reorderLevel: 20,
    },
    {
      medicationCode: 'MED-007',
      name: 'Loratadine',
      genericName: 'Loratadine',
      category: MedicationCategoryEnum.ANTIHISTAMINE,
      description: 'Antihistamine for allergies',
      dosageForm: 'Tablet',
      strength: '10mg',
      manufacturer: 'AllerMeds',
      stockQuantity: 400,
      unit: 'tablets',
      unitPrice: 0.35,
      reorderLevel: 40,
    },
    {
      medicationCode: 'MED-008',
      name: 'Omeprazole',
      genericName: 'Omeprazole',
      category: MedicationCategoryEnum.ANTACID,
      description: 'Proton pump inhibitor for acid reflux',
      dosageForm: 'Capsule',
      strength: '20mg',
      manufacturer: 'GastroMeds',
      stockQuantity: 350,
      unit: 'capsules',
      unitPrice: 0.40,
      reorderLevel: 35,
    },
    {
      medicationCode: 'MED-009',
      name: 'Amlodipine',
      genericName: 'Amlodipine',
      category: MedicationCategoryEnum.ANTIHYPERTENSIVE,
      description: 'Calcium channel blocker for hypertension',
      dosageForm: 'Tablet',
      strength: '5mg',
      manufacturer: 'CardioMeds',
      stockQuantity: 250,
      unit: 'tablets',
      unitPrice: 0.28,
      reorderLevel: 25,
    },
    {
      medicationCode: 'MED-010',
      name: 'Multivitamin',
      genericName: 'Multivitamin Complex',
      category: MedicationCategoryEnum.SUPPLEMENT,
      description: 'Daily multivitamin supplement',
      dosageForm: 'Tablet',
      strength: '1 tablet',
      manufacturer: 'VitaHealth',
      stockQuantity: 150,
      unit: 'tablets',
      unitPrice: 0.45,
      reorderLevel: 15,
    },
  ];

  await medicationModel.insertMany(medications);
  logger.log(`Seeded ${medications.length} medications successfully`);
}
